/*
 * Financial Future Planner
 *
 * This is the HTTP API representation of the financial future planner
 *
 * API version: 0.0.1
 * Contact: nick@nickborgers.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"net/http"
)

func AddBalance(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}
