/*
 * Financial Future Planner
 *
 * This is the HTTP API representation of the financial future planner
 *
 * API version: 0.0.1
 * Contact: nick@nickborgers.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Period struct {

	Start time.Time `json:"start"`

	End time.Time `json:"end"`
}
