/*
 * Financial Future Planner
 *
 * This is the HTTP API representation of the financial future planner
 *
 * API version: 0.0.1
 * Contact: nick@nickborgers.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Balance struct {

	Account string `json:"account,omitempty"`

	Type_ string `json:"type,omitempty"`

	Class string `json:"class,omitempty"`

	Balance float64 `json:"balance,omitempty"`

	FixedRate float32 `json:"fixed_rate,omitempty"`

	Correlary string `json:"correlary,omitempty"`
}
