/*
 * Financial Future Planner
 *
 * This is the HTTP API representation of the financial future planner
 *
 * API version: 0.0.1
 * Contact: nick@nickborgers.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	actual "github.com/NickBorgers/financial-future-planner/pkg"
	"log"
	"net/http"
)

func main() {
	log.Printf("Server started")

	router := actual.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
